import {FIELD_INDEX_BITS, SYMBOLS} from './SETTINGS.js';
import FIELDS from './FIELDS.js';

// =====================================================================================================================
//  P U B L I C
// =====================================================================================================================
/**
 * [Generated by Gemini Flash 3.8]
 * Decodes the symbol string produced by encode() back into the original object.
 * @param {string} symbols
 * @returns {object}
 */
function decode(symbols) {
    if (!symbols) {
        return {};
    }
    const stream = convertSymbolsToBits(symbols);
    const result = {};
    let cursor = 0;
    let expectedIndex = 0;

    while (cursor < stream.length) {
        // Read the sequential flag bit: '1' means sequential, '0' means jump
        const isSequential = stream[cursor++] === '1';

        let currentIndex;
        if (isSequential) {
            currentIndex = expectedIndex;
        } else {
            // Read the jump index
            const indexBits = stream.slice(cursor, cursor + FIELD_INDEX_BITS);
            cursor += FIELD_INDEX_BITS;
            currentIndex = parseInt(indexBits, 2);
        }

        const field = FIELDS[currentIndex];
        if (!field) {
            console.warn(`Invalid field index encountered: ${currentIndex}`);
            return result;
        }

        // Read field value bits
        const valueBits = stream.slice(cursor, cursor + field.bits);
        cursor += field.bits;
        let value = parseInt(valueBits, 2);
        if (field.dictionary) {
            if (value >= field.dictionary.length) {
                console.warn(`Dictionary index ${value} out of bounds for field "${field.key}"!`);
                return result;
            }
            value = field.dictionary[value];
        }
        if (value) {
            result[field.key] = value;
        }

        // Next expected index in sequential order
        expectedIndex = currentIndex + 1;
    }

    return result;
}

// =====================================================================================================================
//  P R I V A T E
// =====================================================================================================================
/**
 * [Generated by Gemini Flash 3.8]
 * Reverses `convertBitsToSymbols` by converting the symbol string back to the original bit string.
 */
function convertSymbolsToBits(symbols) {
    if (!symbols) {
        return '';
    }
    const base = BigInt(SYMBOLS.length);
    let num = 0n;
    for (const char of symbols) {
        const index = SYMBOLS.indexOf(char);
        if (index === -1) {
            console.log(`Invalid symbol encountered: ${char}`);
            return '';
        }
        num = num * base + BigInt(index);
    }
    return num.toString(2).slice(1);
}

// =====================================================================================================================
//  E X P O R T
// =====================================================================================================================

export default decode;
