import DICTIONARY from './DICTIONARY.js';

const FIELDS = [
    /*00*/ {key: 'hero', bits: 8 /*256*/, dictionary: DICTIONARY.heroes},
    /*01*/ {key: 'level', bits: 5 /*32*/},
    /*02*/ {key: 'skill0Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*03*/ {key: 'skill0Sub1', bits: 3 /*8*/},
    /*04*/ {key: 'skill0Sub2', bits: 3 /*8*/},
    /*05*/ {key: 'skill1Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*06*/ {key: 'skill1Sub1', bits: 3 /*8*/},
    /*07*/ {key: 'skill1Sub2', bits: 3 /*8*/},
    /*08*/ {key: 'skill2Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*09*/ {key: 'skill2Sub1', bits: 3 /*8*/},
    /*10*/ {key: 'skill2Sub2', bits: 3 /*8*/},
    /*11*/ {key: 'skill3Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*12*/ {key: 'skill3Sub1', bits: 3 /*8*/},
    /*13*/ {key: 'skill3Sub2', bits: 3 /*8*/},
    /*14*/ {key: 'skill4Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*15*/ {key: 'skill4Sub1', bits: 3 /*8*/},
    /*16*/ {key: 'skill4Sub2', bits: 3 /*8*/},
    /*17*/ {key: 'skill5Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*18*/ {key: 'skill5Sub1', bits: 3 /*8*/},
    /*19*/ {key: 'skill5Sub2', bits: 3 /*8*/},
    /*20*/ {key: 'skill6Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*21*/ {key: 'skill6Sub1', bits: 3 /*8*/},
    /*22*/ {key: 'skill6Sub2', bits: 3 /*8*/},
    /*23*/ {key: 'skill7Id', bits: 6 /*64*/, dictionary: DICTIONARY.skills},
    /*24*/ {key: 'skill7Sub1', bits: 3 /*8*/},
    /*25*/ {key: 'skill7Sub2', bits: 3 /*8*/},
    /*26*/ {key: 'artifactSword', bits: 5 /*32*/, dictionary: DICTIONARY.artifactSword},
    /*27*/ {key: 'artifactShield', bits: 5 /*32*/, dictionary: DICTIONARY.artifactShield},
    /*28*/ {key: 'artifactArmor', bits: 5 /*32*/, dictionary: DICTIONARY.artifactArmor},
    /*29*/ {key: 'artifactHelmet', bits: 5 /*32*/, dictionary: DICTIONARY.artifactHelmet},
    /*30*/ {key: 'artifactBoots', bits: 5 /*32*/, dictionary: DICTIONARY.artifactBoots},
    /*31*/ {key: 'artifactBelt', bits: 5 /*32*/, dictionary: DICTIONARY.artifactBelt},
    /*32*/ {key: 'artifactCape', bits: 5 /*32*/, dictionary: DICTIONARY.artifactCape},
    /*33*/ {key: 'artifactRingL', bits: 5 /*32*/, dictionary: DICTIONARY.artifactRing},
    /*34*/ {key: 'artifactRingR', bits: 5 /*32*/, dictionary: DICTIONARY.artifactRing},
    /*35*/ {key: 'artifactPouchTL', bits: 6 /*64*/, dictionary: DICTIONARY.artifactPouch},
    /*36*/ {key: 'artifactPouchTR', bits: 6 /*64*/, dictionary: DICTIONARY.artifactPouch},
    /*37*/ {key: 'artifactPouchBL', bits: 6 /*64*/, dictionary: DICTIONARY.artifactPouch},
    /*38*/ {key: 'artifactPouchBR', bits: 6 /*64*/, dictionary: DICTIONARY.artifactPouch},
    /*39*/ {key: 'artifactBanner', bits: 5 /*32*/, dictionary: DICTIONARY.artifactBanner},
    /*40*/ {key: 'army0Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*41*/ {key: 'army0Count', bits: 10 /*1024*/},
    /*42*/ {key: 'army1Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*43*/ {key: 'army1Count', bits: 10 /*1024*/},
    /*44*/ {key: 'army2Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*45*/ {key: 'army2Count', bits: 10 /*1024*/},
    /*46*/ {key: 'army3Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*47*/ {key: 'army3Count', bits: 10 /*1024*/},
    /*48*/ {key: 'army4Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*49*/ {key: 'army4Count', bits: 10 /*1024*/},
    /*50*/ {key: 'army5Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*51*/ {key: 'army5Count', bits: 10 /*1024*/},
    /*52*/ {key: 'army6Id', bits: 8 /*256*/, dictionary: DICTIONARY.units},
    /*53*/ {key: 'army6Count', bits: 10 /*1024*/},
];

export default FIELDS;
